using MtgSoloSports.Features.Athletes.GetProfile;
using MtgSoloSports.Features.Athletes.GetRecordHoldings;
using MtgSoloSports.Features.Athletes.SearchAthletes;
using MtgSoloSports.Features.Catalog.GetCatalogStats;
using MtgSoloSports.Features.Catalog.ImportCatalog;
using MtgSoloSports.Features.Catalog.ImportFromScryfall;
using MtgSoloSports.Features.Cups.GetColorCupIndividualResult;
using MtgSoloSports.Features.Cups.GetColorCupSelection;
using MtgSoloSports.Features.Cups.GetColorCupSelectionReport;
using MtgSoloSports.Features.Cups.GetColorCupTeamHistory;
using MtgSoloSports.Features.Cups.GetColorCupTeamResult;
using MtgSoloSports.Features.Cups.GetTypeCupSelection;
using MtgSoloSports.Features.Cups.GetTypeCupSelectionReport;
using MtgSoloSports.Features.Cups.GetTypeCupTeamHistory;
using MtgSoloSports.Features.Cups.GetTypeCupTeamResult;
using MtgSoloSports.Features.Cups.ListCupEditions;
using MtgSoloSports.Features.Cups.PlayColorCupIndividualRound;
using MtgSoloSports.Features.Cups.PlayColorCupTeamRound;
using MtgSoloSports.Features.Cups.PlayTypeCupTeamRound;
using MtgSoloSports.Features.Cups.RunColorCupIndividual;
using MtgSoloSports.Features.Cups.RunColorCupTeam;
using MtgSoloSports.Features.Cups.RunTypeCupTeam;
using MtgSoloSports.Features.Cups.SelectColorCupTeams;
using MtgSoloSports.Features.Cups.SelectTypeCupTeams;
using MtgSoloSports.Features.Diagnostics.LongRunChecksum;
using MtgSoloSports.Features.Diagnostics.LongRunInvariants;
using MtgSoloSports.Features.Diagnostics.LongRunStats;
using MtgSoloSports.Features.History.GetEventRound;
using MtgSoloSports.Features.History.GetEventTeamStandings;
using MtgSoloSports.Features.History.GetRoundReplay;
using MtgSoloSports.Features.History.GetSeasonPlacements;
using MtgSoloSports.Features.History.GetSeasonTable;
using MtgSoloSports.Features.History.GetStageStandings;
using MtgSoloSports.Features.History.ListCompetitions;
using MtgSoloSports.Features.History.ListEventRounds;
using MtgSoloSports.Features.History.ListEvents;
using MtgSoloSports.Features.History.ListRounds;
using MtgSoloSports.Features.History.ListSeasons;
using MtgSoloSports.Features.History.ListStages;
using MtgSoloSports.Features.Leagues.CurrentStandings;
using MtgSoloSports.Features.Leagues.GetSeason1Leagues;
using MtgSoloSports.Features.Leagues.SeasonProgress;
using MtgSoloSports.Features.Leagues.SeasonTable;
using MtgSoloSports.Features.Leagues.UpgradeToTiered;
using MtgSoloSports.Features.Qualifiers;
using MtgSoloSports.Features.Records.GetHallOfFame;
using MtgSoloSports.Features.Records.GetRecords;
using MtgSoloSports.Features.Records.ListHonours;
using MtgSoloSports.Features.Saves.CreateCheckpoint;
using MtgSoloSports.Features.Saves.CreateSave;
using MtgSoloSports.Features.Saves.DeleteSave;
using MtgSoloSports.Features.Saves.ExportSave;
using MtgSoloSports.Features.Saves.ImportSave;
using MtgSoloSports.Features.Saves.ListCheckpoints;
using MtgSoloSports.Features.Saves.ListSaves;
using MtgSoloSports.Features.Saves.OpenSave;
using MtgSoloSports.Features.Saves.RestoreCheckpoint;
using MtgSoloSports.Features.Seasons.AdvanceToNextEvent;
using MtgSoloSports.Features.Seasons.GetSeasonStatus;
using MtgSoloSports.Features.Seasons.StartNextSeason;
using MtgSoloSports.Features.Simulation.AdvanceRound;
using MtgSoloSports.Features.Simulation.CompleteSeason;
using MtgSoloSports.Features.Simulation.CompleteStage;
using MtgSoloSports.Features.Simulation.CompleteStageForAllLeagues;
using MtgSoloSports.Features.Simulation.GetStageRounds;
using MtgSoloSports.Features.Simulation.SimulateSeasons;
using MtgSoloSports.Features.Stories.ListAthleteStories;
using MtgSoloSports.Features.Stories.ListRecent;
using MtgSoloSports.Features.Superleague.CreateInaugural;
using MtgSoloSports.Features.Superleague.GetAutomaticMovement;
using MtgSoloSports.Features.Superleague.GetFeederMovements;
using MtgSoloSports.Features.Superleague.GetInauguralRoster;
using MtgSoloSports.Features.Superleague.GetQualifierResult;
using MtgSoloSports.Features.Superleague.GetRebalanceResult;
using MtgSoloSports.Features.Superleague.PlayQualifierRound;
using MtgSoloSports.Features.Superleague.RebalanceFeeders;
using MtgSoloSports.Features.Superleague.ResolveAutomaticMovement;
using MtgSoloSports.Features.Superleague.RunQualifier;
using MtgSoloSports.Persistence.Catalog;
using MtgSoloSports.Persistence.Saves;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddProblemDetails();
builder.Services.Configure<SaveStorageOptions>(builder.Configuration.GetSection(SaveStorageOptions.SectionName));
builder.Services.Configure<CatalogStorageOptions>(builder.Configuration.GetSection(CatalogStorageOptions.SectionName));
builder.Services.AddSingleton(TimeProvider.System);
builder.Services.AddSingleton<SaveSqliteConnectionInterceptor>();
builder.Services.AddSingleton<SaveDbContextFactory>();
builder.Services.AddSingleton<SaveStore>();
builder.Services.AddSingleton<CatalogDbContextFactory>();
builder.Services.AddSingleton<CatalogStore>();
builder.Services.Configure<ScryfallBulkOptions>(builder.Configuration.GetSection(ScryfallBulkOptions.SectionName));
builder.Services.AddSingleton<ScryfallImportLock>();
builder.Services.AddHttpClient<IScryfallBulkGateway, ScryfallBulkGateway>(client =>
{
    client.Timeout = TimeSpan.FromMinutes(5);
    client.DefaultRequestHeaders.UserAgent.ParseAdd("MtgSoloSports/1.0 (+https://github.com/AlexBDevCorner/MtgSoloSports)");
    client.DefaultRequestHeaders.Accept.ParseAdd("application/json");
});
builder.Services.AddScoped<CreateSaveHandler>();
builder.Services.AddScoped<ListSavesHandler>();
builder.Services.AddScoped<OpenSaveHandler>();
builder.Services.AddScoped<DeleteSaveHandler>();
builder.Services.AddScoped<ExportSaveHandler>();
builder.Services.AddScoped<ImportSaveHandler>();
builder.Services.AddScoped<CreateCheckpointHandler>();
builder.Services.AddScoped<ListCheckpointsHandler>();
builder.Services.AddScoped<RestoreCheckpointHandler>();
builder.Services.AddScoped<ImportCatalogHandler>();
builder.Services.AddScoped<GetCatalogStatsHandler>();
builder.Services.AddScoped<ImportFromScryfallHandler>();
builder.Services.AddScoped<GetSeason1LeaguesHandler>();
builder.Services.AddScoped<UpgradeToTieredHandler>();
builder.Services.AddScoped<AdvanceRoundHandler>();
builder.Services.AddScoped<CompleteStageHandler>();
builder.Services.AddScoped<CompleteStageForAllLeaguesHandler>();
builder.Services.AddScoped<CompleteSeasonHandler>();
builder.Services.AddScoped<SimulateSeasonsHandler>();
builder.Services.AddScoped<GetStageRoundsHandler>();
builder.Services.AddScoped<GetCurrentStandingsHandler>();
builder.Services.AddScoped<GetSeasonTableHandler>();
builder.Services.AddScoped<GetSeasonProgressHandler>();
builder.Services.AddScoped<GetAthleteProfileHandler>();
builder.Services.AddScoped<GetAthleteRecordHoldingsHandler>();
builder.Services.AddScoped<SearchAthletesHandler>();
builder.Services.AddScoped<CreateInauguralSuperleagueHandler>();
builder.Services.AddScoped<GetInauguralRosterHandler>();
builder.Services.AddScoped<ResolveAutomaticMovementHandler>();
builder.Services.AddScoped<GetAutomaticMovementHandler>();
builder.Services.AddScoped<GetFeederMovementsHandler>();
builder.Services.AddScoped<RunQualifierHandler>();
builder.Services.AddScoped<PlayQualifierRoundHandler>();
builder.Services.AddScoped<GetQualifierResultHandler>();
builder.Services.AddScoped<BoundaryQualifierRunner>();
builder.Services.AddScoped<RunAllQualifiersHandler>();
builder.Services.AddScoped<GetQualifierListHandler>();
builder.Services.AddScoped<RebalanceFeedersHandler>();
builder.Services.AddScoped<GetRebalanceResultHandler>();
builder.Services.AddScoped<SelectColorCupTeamsHandler>();
builder.Services.AddScoped<GetColorCupSelectionHandler>();
builder.Services.AddScoped<GetColorCupSelectionReportHandler>();
builder.Services.AddScoped<RunColorCupIndividualHandler>();
builder.Services.AddScoped<PlayColorCupIndividualRoundHandler>();
builder.Services.AddScoped<GetColorCupIndividualResultHandler>();
builder.Services.AddScoped<RunColorCupTeamHandler>();
builder.Services.AddScoped<PlayColorCupTeamRoundHandler>();
builder.Services.AddScoped<GetColorCupTeamResultHandler>();
builder.Services.AddScoped<SelectTypeCupTeamsHandler>();
builder.Services.AddScoped<GetTypeCupSelectionHandler>();
builder.Services.AddScoped<GetTypeCupSelectionReportHandler>();
builder.Services.AddScoped<RunTypeCupTeamHandler>();
builder.Services.AddScoped<PlayTypeCupTeamRoundHandler>();
builder.Services.AddScoped<GetTypeCupTeamResultHandler>();
builder.Services.AddScoped<ListCupEditionsHandler>();
builder.Services.AddScoped<GetColorCupTeamHistoryHandler>();
builder.Services.AddScoped<GetTypeCupTeamHistoryHandler>();
builder.Services.AddScoped<GetSeasonStatusHandler>();
builder.Services.AddScoped<StartNextSeasonHandler>();
builder.Services.AddScoped<AdvanceToNextEventHandler>();
builder.Services.AddScoped<ListHistorySeasonsHandler>();
builder.Services.AddScoped<ListRecentStoriesHandler>();
builder.Services.AddScoped<ListAthleteStoriesHandler>();
builder.Services.AddScoped<ListHistoryCompetitionsHandler>();
builder.Services.AddScoped<ListHistoryStagesHandler>();
builder.Services.AddScoped<ListHistoryRoundsHandler>();
builder.Services.AddScoped<GetHistoryRoundReplayHandler>();
builder.Services.AddScoped<ListHistoryEventsHandler>();
builder.Services.AddScoped<ListHistoryEventRoundsHandler>();
builder.Services.AddScoped<GetHistoryEventRoundHandler>();
builder.Services.AddScoped<GetHistoryEventTeamStandingsHandler>();
builder.Services.AddScoped<GetHistoryStageStandingsHandler>();
builder.Services.AddScoped<GetSeasonPlacementsHandler>();
builder.Services.AddScoped<GetHistorySeasonTableHandler>();
builder.Services.AddScoped<ListHonoursHandler>();
builder.Services.AddScoped<GetRecordsHandler>();
builder.Services.AddScoped<GetHallOfFameHandler>();
builder.Services.AddScoped<GetLongRunChecksumHandler>();
builder.Services.AddScoped<ValidateLongRunInvariantsHandler>();
builder.Services.AddScoped<GetLongRunStatsHandler>();

var app = builder.Build();

app.UseExceptionHandler();
app.UseDefaultFiles();
app.UseStaticFiles();

app.MapGet("/api/health", () => Results.Ok(new { status = "ok" }));

CreateSaveEndpoint.Map(app);
ListSavesEndpoint.Map(app);
OpenSaveEndpoint.Map(app);
DeleteSaveEndpoint.Map(app);
ExportSaveEndpoint.Map(app);
ImportSaveEndpoint.Map(app);
CreateCheckpointEndpoint.Map(app);
ListCheckpointsEndpoint.Map(app);
RestoreCheckpointEndpoint.Map(app);
ImportCatalogEndpoint.Map(app);
GetCatalogStatsEndpoint.Map(app);
ImportFromScryfallEndpoint.Map(app);
GetSeason1LeaguesEndpoint.Map(app);
UpgradeToTieredEndpoint.Map(app);
AdvanceRoundEndpoint.Map(app);
CompleteStageEndpoint.Map(app);
CompleteStageForAllLeaguesEndpoint.Map(app);
CompleteSeasonEndpoint.Map(app);
SimulateSeasonsEndpoint.Map(app);
GetStageRoundsEndpoint.Map(app);
GetCurrentStandingsEndpoint.Map(app);
GetSeasonTableEndpoint.Map(app);
GetSeasonProgressEndpoint.Map(app);
GetAthleteProfileEndpoint.Map(app);
GetAthleteRecordHoldingsEndpoint.Map(app);
SearchAthletesEndpoint.Map(app);
CreateInauguralSuperleagueEndpoint.Map(app);
GetInauguralRosterEndpoint.Map(app);
ResolveAutomaticMovementEndpoint.Map(app);
GetAutomaticMovementEndpoint.Map(app);
GetFeederMovementsEndpoint.Map(app);
RunQualifierEndpoint.Map(app);
PlayQualifierRoundEndpoint.Map(app);
GetQualifierResultEndpoint.Map(app);
RunFeederQualifierEndpoint.Map(app);
GetQualifierListEndpoint.Map(app);
RebalanceFeedersEndpoint.Map(app);
GetRebalanceResultEndpoint.Map(app);
SelectColorCupTeamsEndpoint.Map(app);
GetColorCupSelectionEndpoint.Map(app);
GetColorCupSelectionReportEndpoint.Map(app);
RunColorCupIndividualEndpoint.Map(app);
PlayColorCupIndividualRoundEndpoint.Map(app);
GetColorCupIndividualResultEndpoint.Map(app);
RunColorCupTeamEndpoint.Map(app);
PlayColorCupTeamRoundEndpoint.Map(app);
GetColorCupTeamResultEndpoint.Map(app);
SelectTypeCupTeamsEndpoint.Map(app);
GetTypeCupSelectionEndpoint.Map(app);
GetTypeCupSelectionReportEndpoint.Map(app);
RunTypeCupTeamEndpoint.Map(app);
PlayTypeCupTeamRoundEndpoint.Map(app);
GetTypeCupTeamResultEndpoint.Map(app);
ListCupEditionsEndpoint.Map(app);
GetColorCupTeamHistoryEndpoint.Map(app);
GetTypeCupTeamHistoryEndpoint.Map(app);
GetSeasonStatusEndpoint.Map(app);
StartNextSeasonEndpoint.Map(app);
AdvanceToNextEventEndpoint.Map(app);
ListHistorySeasonsEndpoint.Map(app);
ListRecentStoriesEndpoint.Map(app);
ListAthleteStoriesEndpoint.Map(app);
ListHistoryCompetitionsEndpoint.Map(app);
ListHistoryStagesEndpoint.Map(app);
ListHistoryRoundsEndpoint.Map(app);
GetHistoryRoundReplayEndpoint.Map(app);
ListHistoryEventsEndpoint.Map(app);
ListHistoryEventRoundsEndpoint.Map(app);
GetHistoryEventRoundEndpoint.Map(app);
GetHistoryEventTeamStandingsEndpoint.Map(app);
GetHistoryStageStandingsEndpoint.Map(app);
GetSeasonPlacementsEndpoint.Map(app);
GetHistorySeasonTableEndpoint.Map(app);
ListHonoursEndpoint.Map(app);
GetRecordsEndpoint.Map(app);
GetHallOfFameEndpoint.Map(app);
GetLongRunChecksumEndpoint.Map(app);
ValidateLongRunInvariantsEndpoint.Map(app);
GetLongRunStatsEndpoint.Map(app);

// MSS-040: unknown /api routes stay JSON 404s so the SPA fallback never masks
// server errors. Valid UI routes fall through to index.html for deep links.
app.MapFallback("/api/{*path}", () => Results.NotFound(new { error = "Unknown API route." }));

app.MapFallbackToFile("index.html");

app.Run();

public partial class Program;
