// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgSoloSports.Persistence.Saves;

#nullable disable

namespace MtgSoloSports.Persistence.Saves.Migrations
{
    [DbContext(typeof(SaveDbContext))]
    [Migration("20260926120000_AddSaveAthletes")]
    partial class AddSaveAthletes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.RngStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AlgorithmVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Stream")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RngStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_RngStates_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.RulesSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RulesSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_RulesSnapshots_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.SaveMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentSeason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaveId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaveMetadata", null, t =>
                        {
                            t.HasCheckConstraint("CK_SaveMetadata_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.SaveAthleteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatureTypesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontColors")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDevoid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHybridMana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArtifact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SportingColor");

                    b.ToTable("SaveAthletes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
