// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgSoloSports.Persistence.Saves;

#nullable disable

namespace MtgSoloSports.Persistence.Saves.Migrations
{
    [DbContext(typeof(SaveDbContext))]
    [Migration("20261006233041_AddTypeCupTournamentFormat")]
    partial class AddTypeCupTournamentFormat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.AthleteCareerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestSeasonFinish")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentEffectiveBonusThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentLeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentLeagueKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentLeagueName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastStageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LifetimeEarnedBonusThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageThirds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageWins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SaveAthleteId")
                        .IsUnique();

                    b.ToTable("AthleteCareers", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.AthleteSeasonSummaryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EarnedBonusThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChampion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeagueKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageThirds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBaseScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalChampionshipPointsThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalStageScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId", "SeasonNumber");

                    b.HasIndex("SeasonId", "LeagueId");

                    b.HasIndex("SeasonId", "SaveAthleteId")
                        .IsUnique();

                    b.ToTable("AthleteSeasonSummaries", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.ColorCupIndividualRoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RngAfterState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterStream")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeStream")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("ColorCupIndividualRounds", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.ColorCupIndividualStandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CupRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CupScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Medal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectionRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "CupRank")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "SaveAthleteId")
                        .IsUnique();

                    b.ToTable("ColorCupIndividualStandings", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.ColorCupSelectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusNormThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusRawThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinalRatingThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormNormThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormRaw")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceNormThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceRawThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestigeNormThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestigeRaw")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectionRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "SportingColor", "SaveAthleteId")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "SportingColor", "SelectionRank")
                        .IsUnique();

                    b.ToTable("ColorCupSelections", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.ColorCupTeamGroupStandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectionRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "SaveAthleteId")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "GroupNumber", "GroupRank")
                        .IsUnique();

                    b.ToTable("ColorCupTeamGroupStandings", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.ColorCupTeamRoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RngAfterState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterStream")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeStream")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "GroupNumber", "RoundNumber")
                        .IsUnique();

                    b.ToTable("ColorCupTeamRounds", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.ColorCupTeamStandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Medal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBaseThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "SportingColor")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "TeamRank")
                        .IsUnique();

                    b.ToTable("ColorCupTeamStandings", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.CupSelectionReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cup")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSeasonId")
                        .IsUnique();

                    b.ToTable("CupSelectionReports", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.HonourEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonNumber");

                    b.HasIndex("SaveAthleteId", "Kind");

                    b.HasIndex("SeasonId", "LeagueId", "SaveAthleteId", "Kind")
                        .IsUnique();

                    b.ToTable("Honours", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.LeagueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeederDivision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeasonId", "Kind", "FeederDivision", "SportingColor")
                        .IsUnique();

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.MovementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromLeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromSeasonRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToLeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToSeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromSeasonId", "FromLeagueId");

                    b.HasIndex("ToSeasonId", "ToLeagueId");

                    b.HasIndex("SaveAthleteId", "ToSeasonId", "Kind");

                    b.HasIndex("ToSeasonId", "SaveAthleteId", "Kind")
                        .IsUnique();

                    b.ToTable("Movements", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.QualifierRoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QualifierBoundary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualifierSportingColor")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterStream")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeStream")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToSeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromSeasonId", "ToSeasonId");

                    b.HasIndex("FromSeasonId", "ToSeasonId", "QualifierBoundary", "QualifierSportingColor");

                    b.HasIndex("FromSeasonId", "ToSeasonId", "QualifierBoundary", "QualifierSportingColor", "RoundNumber")
                        .IsUnique();

                    b.ToTable("QualifierRounds", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.QualifierStandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromLeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromSeasonRank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQualified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualifierBoundary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualifierRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualifierScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualifierSportingColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToSeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId");

                    b.HasIndex("FromSeasonId", "ToSeasonId");

                    b.HasIndex("FromSeasonId", "ToSeasonId", "QualifierBoundary", "QualifierSportingColor");

                    b.HasIndex("FromSeasonId", "ToSeasonId", "QualifierBoundary", "QualifierSportingColor", "QualifierRank")
                        .IsUnique();

                    b.HasIndex("FromSeasonId", "ToSeasonId", "QualifierBoundary", "QualifierSportingColor", "SaveAthleteId")
                        .IsUnique();

                    b.ToTable("QualifierStandings", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.RngStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AlgorithmVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Stream")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RngStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_RngStates_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.RoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RngAfterState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterStream")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeStream")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("SeasonId", "LeagueId", "StageNumber");

                    b.HasIndex("SeasonId", "LeagueId", "StageNumber", "RoundNumber")
                        .IsUnique();

                    b.ToTable("Rounds", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.RulesSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RulesSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_RulesSnapshots_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.SaveAthleteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatureTypesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontColors")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDevoid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHybridMana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArtifact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SetCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeCupNationality")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SportingColor");

                    b.ToTable("SaveAthletes", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.SaveMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentSeason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaveId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaveMetadata", null, t =>
                        {
                            t.HasCheckConstraint("CK_SaveMetadata_SingleRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.SeasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSuperleague")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonNumber")
                        .IsUnique();

                    b.ToTable("Seasons", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.SeasonMembershipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrawIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportingColor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId");

                    b.HasIndex("SeasonId", "LeagueId");

                    b.HasIndex("SeasonId", "SaveAthleteId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "SportingColor");

                    b.HasIndex("SeasonId", "LeagueId", "DrawIndex");

                    b.ToTable("SeasonMemberships", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.SeasonStandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChampion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StagePlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StageWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBaseScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalChampionshipPointsThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalStageScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId");

                    b.HasIndex("SeasonId", "LeagueId");

                    b.HasIndex("SeasonId", "LeagueId", "SaveAthleteId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "LeagueId", "SeasonRank")
                        .IsUnique();

                    b.ToTable("SeasonStandings", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.StageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedRounds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "LeagueId");

                    b.HasIndex("SeasonId", "LeagueId", "StageNumber")
                        .IsUnique();

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.StageStandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampionshipPointsThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EarnedBonusThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("SaveAthleteId", "SeasonId");

                    b.HasIndex("SeasonId", "LeagueId", "StageNumber");

                    b.HasIndex("SeasonId", "LeagueId", "StageNumber", "SaveAthleteId")
                        .IsUnique();

                    b.ToTable("StageStandings", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.StoryEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StageNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId", "Id");

                    b.HasIndex("SeasonNumber", "Id");

                    b.HasIndex("SaveAthleteId", "EventType", "DedupKey")
                        .IsUnique();

                    b.ToTable("StoryEvents", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.TypeCupSelectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusNormThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusRawThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalRatingThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormNormThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormRaw")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceNormThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceRawThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestigeNormThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestigeRaw")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectionRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeRank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "SaveAthleteId")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "CreatureType", "SaveAthleteId")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "CreatureType", "SelectionRank")
                        .IsUnique();

                    b.ToTable("TypeCupSelections", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.TypeCupTeamGroupStandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveAthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectionRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentPhase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveAthleteId");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "TournamentPhase", "QualificationGroup", "SaveAthleteId")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "TournamentPhase", "QualificationGroup", "GroupNumber", "GroupRank")
                        .IsUnique();

                    b.ToTable("TypeCupTeamGroupStandings", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.TypeCupTeamRoundEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationGroup")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterStream")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeStream")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentPhase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "TournamentPhase", "QualificationGroup", "GroupNumber", "RoundNumber")
                        .IsUnique();

                    b.ToTable("TypeCupTeamRounds", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.TypeCupTeamStandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Medal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundPlaceCountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBaseThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamScoreThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentPhase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "TournamentPhase", "QualificationGroup", "CreatureType")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "TournamentPhase", "QualificationGroup", "TeamRank")
                        .IsUnique();

                    b.ToTable("TypeCupTeamStandings", (string)null);
                });

            modelBuilder.Entity("MtgSoloSports.Persistence.Saves.TypeCupTournamentDrawEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrawChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldTeamCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FinalPlacesForGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationGroupCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngAfterStream")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RngBeforeStream")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentFormatVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSeasonId");

                    b.HasIndex("SourceSeasonId", "CreatureType")
                        .IsUnique();

                    b.HasIndex("SourceSeasonId", "QualificationGroup");

                    b.ToTable("TypeCupTournamentDraws", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
